#!/bin/bash
# --------------------------------------
# 目的
# - グローバルにRailsをインストールせずに、Bundlerを使ってプロジェクトディレクトリにRails:newする
# - git init & gitignore
# 
# 条件
# - Bundlerがグローバルにインストールされていること
# 
# 使い方
# rails_new [APPNAME]
# 
# TODO
# - railsと依存のgemを2回インストールしているので無駄かも。最初にDLしたものをコピーしてうまくいくだろうか？
# --------------------------------------
 
TEMP_DIR=_rails_new_temp
app_name=$1
 
if [ -d $app_name ]; then
  echo "[ERROR] ディレクトリ[$app_name]が既に存在します"
  exit
fi
 
mkdir $TEMP_DIR
cd $TEMP_DIR
bundle init
echo 'gem "rails"' >> Gemfile
bundle install --path=vendor/bundle
bundle exec rails new $app_name --skip-bundle
cd $app_name
bundle install --path=vendor/bundle --binstubs=vendor/bin
cd ../../
mv $TEMP_DIR/$app_name ./
rm -rf $TEMP_DIR
 
# git ---------
# git関係をやりたくない場合はここを消してください
cd $app_name
git init
rm .gitignore
cat << EOT >> .gitignore
*.DS_Store
*.rbc
*.sassc
/.bundle
/brakeman.html
/db/*.sqlite3
/log/*.log
/vendor/*
/log/*
/tmp/*
/db/*.sqlite3
/public/system/*
/public/uploads/*
/coverage/
/spec/tmp/*
.sass-cache
.rspec
.project
capybara-*.html
EOT
git add --all
git commit -m 'Initialize with rails (auto commit by rails_new)'
# /git ---------
 
exit 0